package io.falu.models.payments;

/**
 * Details about an MPESA Payment
 */
public class MpesaPayment {
    /**
     * The target MPESA business short code.
     */
    public String businessShortCode;

    /**
     * Unique identifier for request as issued by MPESA.
     * Only populated for flows that initiate the transaction instead of MPESA.
     * The value is only available after the request is sent to MPESA.
     * This is also referred to as the {ConversationId}.
     */
    public String requestId;

    /**
     * Unique transaction identifier generated by MPESA. Only populated for completed transactions.
     */
    public String receipt;

    /**
     * Name of the entity making or that made the payment.
     */
    public String payer;

    /**
     * Reference the payment was made in.
     */
    public String reference;

    /**
     * Type of payment.
     */
    public MpeaPaymentType type;

    /**
     * Phone number that made the payment, in E.164 format.
     */
    public String phone;
}
