version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
    open-pull-requests-limit: 10
    ignore:
    - dependency-name: "mockito-*"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "junit-*"
      update-types: ["version-update:semver-patch"]
