version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "02:00"
    open-pull-requests-limit: 20
    reviewers:
      - mburumaxwell
    groups:
      test-framework:
        patterns:
          - "mockito*"
          - "junit*"
          - "org.junit.jupiter*"
    ignore:
      - dependency-name: "mockito*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "junit*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "org.junit.jupiter*"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
      time: "02:00"
    open-pull-requests-limit: 10
    reviewers:
      - mburumaxwell
