name: Build

on:
  push:
    tags:
      - '*'
    paths-ignore: # do not trigger for changes:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - docs/**
  pull_request:
    branches: [ main ]
    paths-ignore: # do not trigger for changes:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - docs/**

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for GitVersion

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: '6.0.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.1.1
        with:
          useConfigFile: true

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        if: ${{ github.event_name == 'pull_request' }}
        run: ./gradlew build --stacktrace

      - name: Publish To maven central
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        run: ./gradlew publish --max-workers 1 closeAndReleaseStagingRepositories --stacktrace
        env:
          NEXUS_PROFILE_ID: ${{ secrets.NEXUS_PROFILE_ID }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          VERSION_NAME: ${{ steps.gitversion.outputs.semVer }}
